server.port=8021
management.server.port=8021

#######################################
#	Database
#######################################
data.mongodb.uri=mongodb://mongoadmin:secret@localhost:27888
data.mongodb.schema-name=FSE_GTW

#######################################
#			Client Config
#######################################
eds-ingestion.url.host=http://localhost:9087
gtw-config.url.host=http://localhost:8018
gtw-broker.url.host=http://localhost:9050

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console

########OPENTELEMETRY################################
otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none

otel.propagators=tracecontext,baggage