server.port=8021
management.server.port=8021

#######################################
#	Database
#######################################
spring.data.mongodb.uri=mongodb://mongo:27017
spring.data.mongodb.database=FSE_GTW

#######################################
#			Client Config
#######################################
gtw-config.url.host=http://it-fse-gtw-config:8018
srv-broker.url.host=http://it-fse-srv-broker:9009

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console

########OPENTELEMETRY################################
otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none

otel.propagators=tracecontext,baggage