server.port=8021
management.server.port=8021

#######################################
#	Database
#######################################
spring.data.mongodb.uri=mongodb://mongo:27017
spring.data.mongodb.database=FSE_GTW

#######################################
#			Client Config
#######################################
gtw-config.url.host=http://it-fse-gtw-config:8018
srv-broker.url.host=http://it-fse-srv-broker:9009

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console
log.kafka-log.enable=true
kafka.log.base-topic=MDS-SA-0004_FU_001_LOG
kafka.producer.client-id=springboot-gtw-eds-client
kafka.bootstrap-servers=kafka:29092
kafka.properties.security.protocol=PLAINTEXT
kafka.properties.sasl.mechanism=PLAIN
kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='' password='';
kafka.properties.ssl.truststore.location=
kafka.properties.ssl.truststore.password=

########OPENTELEMETRY################################
otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none

otel.propagators=tracecontext,baggage
